export { Construct } from './construct/Construct'
export { Binary } from './binary/Binary'
export { MoneyFlow } from './money-flow/MoneyFlow'
export { Partners } from './partners/Partners'
export { Withdraws } from './withdraws/Withdraws'
export { Price } from './price/Price'
export { About } from './about/About'
export { Bids } from './bids/Bids'
export { CharityFund } from './charity-fund/CharityFund'
export { Courses } from './courses/Courses'
export { Health } from './health/Health'
export { News } from './news/News'
export { OurTeam } from './our-team/OurTeam'
// export { Partners } from './partners-deprecated/Partners'
export { Program } from './program/Program'
export { Resort } from './resort/Resort'
export { Resorts } from './resorts/Resorts'
export { Home } from './home/Home'
export { Login } from './login/Login'
export { NotFound } from './not-found/NotFound'
export { Levels } from './levels/Levels'
export { Services } from './services/Services'
export { Replenish } from './replenish/Replenish'
export { CoursesResorts } from './courses/CourseResorts'
export { Bonuses } from './bonuses/Bonuses'
export { Fund } from './fund/Fund'
export { HealthWorld } from './health-world/HealthWorld'
export { Tours } from './tours/Tours'
export { Rights } from './rights/Rights'
export { Dual } from './dual/Dual'

export { CharityFundKz } from './charity-fund/CharityfundKz'
export { AboutKz } from './about/AboutKz'
export { ProgramKz } from './program/ProgramKz'
export { HealthKz } from './health/HealthKz'
export { HomeKz } from './home/HomeKz'
export { PriceKz } from './price/PriceKz'
export { OurTeamKz } from './our-team/OurTeamKz'
export { ConstructKz } from './construct/ConstructKz'
export { NewsKz } from './news/NewsKz'
export { CoursesKz } from './courses/CoursesKz'
// export { PartnersKz } from './partners-deprecated/PartnersKz'
export { CoursesResortsKz } from './courses/CourseResortsKz'
export { HealthWorldKz } from './health-world/HealthWorldKz'
export { FundKz } from './fund/FundKz'
export { DualKz } from './dual/DualKz'

export { Tester } from './tester/Tester'
export { ProfileCourses } from './profile-courses/ProfileCourses'

export { Agents } from './agents/Agents'
export { AgentsBids } from './agents/AgentsBids'

export { Tourist } from './tourist/Tourist'

export { Users } from './users/Users'

export { Market } from './market/market'
export { Users as Marketsers } from './market/users'
export { Shops } from './market/shops'
export { Categories } from './market/categories'
export { Products } from './market/products'
export { AllShops } from './market/all-shops'